### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by engsr6982** [engsr6982/LLSE-workspace#29]
## Issue
- [x] engsr6982/lse-workspace#30
- [x] engsr6982/lse-workspace#31
- [x] engsr6982/lse-workspace#32
- [ ] engsr6982/LeviTPSystem#1
- [x] engsr6982/lse-workspace#34
- [x] engsr6982/lse-workspace#35
